// Implementation file for parser generated by fsyacc
module CalculatorParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 2 "CalculatorParser.fsp"

open CalculatorTypesAST

# 10 "CalculatorParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | TIMES
  | DIV
  | PLUS
  | MINUS
  | POW
  | LPAR
  | RPAR
  | EOF
  | LBRAK
  | RBRAK
  | ASSIGN
  | SKIP
  | ORDER
  | IF
  | FI
  | DO
  | OD
  | IFTHEN
  | FATBAR
  | BITWISEAND
  | BITWISEOR
  | AND
  | OR
  | NEG
  | EQUAL
  | NOTEQUAL
  | LGREATER
  | LGREATEREQUAL
  | RGREATER
  | RGREATEREQUAL
  | FALSE
  | TRUE
  | NUM of (float)
  | VARIABLE of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_TIMES
    | TOKEN_DIV
    | TOKEN_PLUS
    | TOKEN_MINUS
    | TOKEN_POW
    | TOKEN_LPAR
    | TOKEN_RPAR
    | TOKEN_EOF
    | TOKEN_LBRAK
    | TOKEN_RBRAK
    | TOKEN_ASSIGN
    | TOKEN_SKIP
    | TOKEN_ORDER
    | TOKEN_IF
    | TOKEN_FI
    | TOKEN_DO
    | TOKEN_OD
    | TOKEN_IFTHEN
    | TOKEN_FATBAR
    | TOKEN_BITWISEAND
    | TOKEN_BITWISEOR
    | TOKEN_AND
    | TOKEN_OR
    | TOKEN_NEG
    | TOKEN_EQUAL
    | TOKEN_NOTEQUAL
    | TOKEN_LGREATER
    | TOKEN_LGREATEREQUAL
    | TOKEN_RGREATER
    | TOKEN_RGREATEREQUAL
    | TOKEN_FALSE
    | TOKEN_TRUE
    | TOKEN_NUM
    | TOKEN_VARIABLE
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_booleanexpr
    | NONTERM_expression

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | TIMES  -> 0 
  | DIV  -> 1 
  | PLUS  -> 2 
  | MINUS  -> 3 
  | POW  -> 4 
  | LPAR  -> 5 
  | RPAR  -> 6 
  | EOF  -> 7 
  | LBRAK  -> 8 
  | RBRAK  -> 9 
  | ASSIGN  -> 10 
  | SKIP  -> 11 
  | ORDER  -> 12 
  | IF  -> 13 
  | FI  -> 14 
  | DO  -> 15 
  | OD  -> 16 
  | IFTHEN  -> 17 
  | FATBAR  -> 18 
  | BITWISEAND  -> 19 
  | BITWISEOR  -> 20 
  | AND  -> 21 
  | OR  -> 22 
  | NEG  -> 23 
  | EQUAL  -> 24 
  | NOTEQUAL  -> 25 
  | LGREATER  -> 26 
  | LGREATEREQUAL  -> 27 
  | RGREATER  -> 28 
  | RGREATEREQUAL  -> 29 
  | FALSE  -> 30 
  | TRUE  -> 31 
  | NUM _ -> 32 
  | VARIABLE _ -> 33 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_TIMES 
  | 1 -> TOKEN_DIV 
  | 2 -> TOKEN_PLUS 
  | 3 -> TOKEN_MINUS 
  | 4 -> TOKEN_POW 
  | 5 -> TOKEN_LPAR 
  | 6 -> TOKEN_RPAR 
  | 7 -> TOKEN_EOF 
  | 8 -> TOKEN_LBRAK 
  | 9 -> TOKEN_RBRAK 
  | 10 -> TOKEN_ASSIGN 
  | 11 -> TOKEN_SKIP 
  | 12 -> TOKEN_ORDER 
  | 13 -> TOKEN_IF 
  | 14 -> TOKEN_FI 
  | 15 -> TOKEN_DO 
  | 16 -> TOKEN_OD 
  | 17 -> TOKEN_IFTHEN 
  | 18 -> TOKEN_FATBAR 
  | 19 -> TOKEN_BITWISEAND 
  | 20 -> TOKEN_BITWISEOR 
  | 21 -> TOKEN_AND 
  | 22 -> TOKEN_OR 
  | 23 -> TOKEN_NEG 
  | 24 -> TOKEN_EQUAL 
  | 25 -> TOKEN_NOTEQUAL 
  | 26 -> TOKEN_LGREATER 
  | 27 -> TOKEN_LGREATEREQUAL 
  | 28 -> TOKEN_RGREATER 
  | 29 -> TOKEN_RGREATEREQUAL 
  | 30 -> TOKEN_FALSE 
  | 31 -> TOKEN_TRUE 
  | 32 -> TOKEN_NUM 
  | 33 -> TOKEN_VARIABLE 
  | 36 -> TOKEN_end_of_input
  | 34 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_booleanexpr 
    | 3 -> NONTERM_booleanexpr 
    | 4 -> NONTERM_booleanexpr 
    | 5 -> NONTERM_booleanexpr 
    | 6 -> NONTERM_booleanexpr 
    | 7 -> NONTERM_booleanexpr 
    | 8 -> NONTERM_booleanexpr 
    | 9 -> NONTERM_booleanexpr 
    | 10 -> NONTERM_booleanexpr 
    | 11 -> NONTERM_booleanexpr 
    | 12 -> NONTERM_booleanexpr 
    | 13 -> NONTERM_booleanexpr 
    | 14 -> NONTERM_booleanexpr 
    | 15 -> NONTERM_booleanexpr 
    | 16 -> NONTERM_expression 
    | 17 -> NONTERM_expression 
    | 18 -> NONTERM_expression 
    | 19 -> NONTERM_expression 
    | 20 -> NONTERM_expression 
    | 21 -> NONTERM_expression 
    | 22 -> NONTERM_expression 
    | 23 -> NONTERM_expression 
    | 24 -> NONTERM_expression 
    | 25 -> NONTERM_expression 
    | 26 -> NONTERM_expression 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 36 
let _fsyacc_tagOfErrorTerminal = 34

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | TIMES  -> "TIMES" 
  | DIV  -> "DIV" 
  | PLUS  -> "PLUS" 
  | MINUS  -> "MINUS" 
  | POW  -> "POW" 
  | LPAR  -> "LPAR" 
  | RPAR  -> "RPAR" 
  | EOF  -> "EOF" 
  | LBRAK  -> "LBRAK" 
  | RBRAK  -> "RBRAK" 
  | ASSIGN  -> "ASSIGN" 
  | SKIP  -> "SKIP" 
  | ORDER  -> "ORDER" 
  | IF  -> "IF" 
  | FI  -> "FI" 
  | DO  -> "DO" 
  | OD  -> "OD" 
  | IFTHEN  -> "IFTHEN" 
  | FATBAR  -> "FATBAR" 
  | BITWISEAND  -> "BITWISEAND" 
  | BITWISEOR  -> "BITWISEOR" 
  | AND  -> "AND" 
  | OR  -> "OR" 
  | NEG  -> "NEG" 
  | EQUAL  -> "EQUAL" 
  | NOTEQUAL  -> "NOTEQUAL" 
  | LGREATER  -> "LGREATER" 
  | LGREATEREQUAL  -> "LGREATEREQUAL" 
  | RGREATER  -> "RGREATER" 
  | RGREATEREQUAL  -> "RGREATEREQUAL" 
  | FALSE  -> "FALSE" 
  | TRUE  -> "TRUE" 
  | NUM _ -> "NUM" 
  | VARIABLE _ -> "VARIABLE" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | TIMES  -> (null : System.Object) 
  | DIV  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | POW  -> (null : System.Object) 
  | LPAR  -> (null : System.Object) 
  | RPAR  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | LBRAK  -> (null : System.Object) 
  | RBRAK  -> (null : System.Object) 
  | ASSIGN  -> (null : System.Object) 
  | SKIP  -> (null : System.Object) 
  | ORDER  -> (null : System.Object) 
  | IF  -> (null : System.Object) 
  | FI  -> (null : System.Object) 
  | DO  -> (null : System.Object) 
  | OD  -> (null : System.Object) 
  | IFTHEN  -> (null : System.Object) 
  | FATBAR  -> (null : System.Object) 
  | BITWISEAND  -> (null : System.Object) 
  | BITWISEOR  -> (null : System.Object) 
  | AND  -> (null : System.Object) 
  | OR  -> (null : System.Object) 
  | NEG  -> (null : System.Object) 
  | EQUAL  -> (null : System.Object) 
  | NOTEQUAL  -> (null : System.Object) 
  | LGREATER  -> (null : System.Object) 
  | LGREATEREQUAL  -> (null : System.Object) 
  | RGREATER  -> (null : System.Object) 
  | RGREATEREQUAL  -> (null : System.Object) 
  | FALSE  -> (null : System.Object) 
  | TRUE  -> (null : System.Object) 
  | NUM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | VARIABLE _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 0us; 65535us; 10us; 65535us; 0us; 2us; 13us; 4us; 14us; 5us; 15us; 6us; 16us; 7us; 17us; 8us; 18us; 9us; 19us; 10us; 22us; 11us; 24us; 12us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 4us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 6us; 1us; 16us; 17us; 18us; 19us; 20us; 1us; 1us; 6us; 16us; 16us; 17us; 18us; 19us; 20us; 6us; 16us; 17us; 17us; 18us; 19us; 20us; 6us; 16us; 17us; 18us; 18us; 19us; 20us; 6us; 16us; 17us; 18us; 19us; 19us; 20us; 6us; 16us; 17us; 18us; 19us; 20us; 20us; 6us; 16us; 17us; 18us; 19us; 20us; 21us; 6us; 16us; 17us; 18us; 19us; 20us; 22us; 6us; 16us; 17us; 18us; 19us; 20us; 25us; 6us; 16us; 17us; 18us; 19us; 20us; 26us; 1us; 16us; 1us; 17us; 1us; 18us; 1us; 19us; 1us; 20us; 1us; 21us; 1us; 22us; 1us; 23us; 2us; 24us; 26us; 1us; 25us; 1us; 25us; 1us; 26us; 1us; 26us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 11us; 13us; 20us; 27us; 34us; 41us; 48us; 55us; 62us; 69us; 76us; 78us; 80us; 82us; 84us; 86us; 88us; 90us; 92us; 95us; 97us; 99us; 101us; |]
let _fsyacc_action_rows = 26
let _fsyacc_actionTableElements = [|5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 0us; 49152us; 6us; 32768us; 0us; 13us; 1us; 14us; 2us; 15us; 3us; 16us; 4us; 17us; 7us; 3us; 0us; 16385us; 1us; 16400us; 4us; 17us; 1us; 16401us; 4us; 17us; 3us; 16402us; 0us; 13us; 1us; 14us; 4us; 17us; 3us; 16403us; 0us; 13us; 1us; 14us; 4us; 17us; 1us; 16404us; 4us; 17us; 3us; 16405us; 0us; 13us; 1us; 14us; 4us; 17us; 3us; 16406us; 0us; 13us; 1us; 14us; 4us; 17us; 6us; 32768us; 0us; 13us; 1us; 14us; 2us; 15us; 3us; 16us; 4us; 17us; 6us; 23us; 6us; 32768us; 0us; 13us; 1us; 14us; 2us; 15us; 3us; 16us; 4us; 17us; 9us; 25us; 5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 0us; 16407us; 1us; 16408us; 8us; 24us; 5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 0us; 16409us; 5us; 32768us; 2us; 18us; 3us; 19us; 5us; 22us; 32us; 20us; 33us; 21us; 0us; 16410us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 6us; 7us; 14us; 15us; 17us; 19us; 23us; 27us; 29us; 33us; 37us; 44us; 51us; 57us; 63us; 69us; 75us; 81us; 87us; 93us; 94us; 96us; 102us; 103us; 109us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 1us; 3us; 3us; 3us; 3us; 2us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 2us; 2us; 1us; 1us; 3us; 4us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; 3us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16407us; 65535us; 65535us; 16409us; 65535us; 16410us; |]
let _fsyacc_reductions ()  =    [| 
# 292 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 301 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "CalculatorParser.fsp"
                                                         _1 
                   )
# 38 "CalculatorParser.fsp"
                 : expr));
# 312 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "CalculatorParser.fsp"
                                True 
                   )
# 56 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 322 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "CalculatorParser.fsp"
                                 False 
                   )
# 57 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 332 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "CalculatorParser.fsp"
                                                                 BitWiseAnd(_1,_3) 
                   )
# 58 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 344 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 59 "CalculatorParser.fsp"
                                                                 BitWiseOr(_1,_3) 
                   )
# 59 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 356 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 60 "CalculatorParser.fsp"
                                                                 LogAnd(_1,_3) 
                   )
# 60 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 368 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "CalculatorParser.fsp"
                                                                 LogOr(_1,_3) 
                   )
# 61 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 380 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 62 "CalculatorParser.fsp"
                                                                 Neg(_2) 
                   )
# 62 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 391 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 63 "CalculatorParser.fsp"
                                                                 Equal(_1,_3) 
                   )
# 63 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 403 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "CalculatorParser.fsp"
                                                                 NotEqual(_1,_3) 
                   )
# 64 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 415 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "CalculatorParser.fsp"
                                                                 LeftGreater(_1,_3) 
                   )
# 65 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 427 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 66 "CalculatorParser.fsp"
                                                                 LeftGreaterEqual(_1,_3) 
                   )
# 66 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 439 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 67 "CalculatorParser.fsp"
                                                                 RightGreater(_1,_3) 
                   )
# 67 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 451 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 68 "CalculatorParser.fsp"
                                                                 RightGreaterEqual(_1,_3) 
                   )
# 68 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 463 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'booleanexpr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 69 "CalculatorParser.fsp"
                                                                 _2 
                   )
# 69 "CalculatorParser.fsp"
                 : 'booleanexpr));
# 474 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 90 "CalculatorParser.fsp"
                                                         TimesExpr(_1,_3) 
                   )
# 90 "CalculatorParser.fsp"
                 : expr));
# 486 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 91 "CalculatorParser.fsp"
                                                         DivExpr(_1,_3) 
                   )
# 91 "CalculatorParser.fsp"
                 : expr));
# 498 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 92 "CalculatorParser.fsp"
                                                         PlusExpr(_1,_3) 
                   )
# 92 "CalculatorParser.fsp"
                 : expr));
# 510 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 93 "CalculatorParser.fsp"
                                                         MinusExpr(_1,_3) 
                   )
# 93 "CalculatorParser.fsp"
                 : expr));
# 522 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 94 "CalculatorParser.fsp"
                                                         PowExpr(_1,_3) 
                   )
# 94 "CalculatorParser.fsp"
                 : expr));
# 534 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 95 "CalculatorParser.fsp"
                                                         UPlusExpr(_2) 
                   )
# 95 "CalculatorParser.fsp"
                 : expr));
# 545 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 96 "CalculatorParser.fsp"
                                                         UMinusExpr(_2) 
                   )
# 96 "CalculatorParser.fsp"
                 : expr));
# 556 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : float)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 97 "CalculatorParser.fsp"
                                                         Num(_1) 
                   )
# 97 "CalculatorParser.fsp"
                 : expr));
# 567 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 98 "CalculatorParser.fsp"
                                                         Var(_1) 
                   )
# 98 "CalculatorParser.fsp"
                 : expr));
# 578 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 99 "CalculatorParser.fsp"
                                                         _2 
                   )
# 99 "CalculatorParser.fsp"
                 : expr));
# 589 "CalculatorParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : expr)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 101 "CalculatorParser.fsp"
                                                                 AccessExpr(_1,_3) 
                   )
# 101 "CalculatorParser.fsp"
                 : expr));
|]
# 602 "CalculatorParser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 37;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : expr =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
